services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: habit_tracker
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"