server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: habit-service
          uri: lb://HABIT-SERVICE
          predicates:
            - Path=/habits/**

        - id: tracking-service
          uri: lb://TRACKING-SERVICE
          predicates:
            - Path=/tracking/**

        - id: analytics-service
          uri: lb://ANALYTICS-SERVICE
          predicates:
            - Path=/analytics/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka