spring.application.name=analytics-service

server.port=8084
spring.data.mongodb.uri=mongodb://localhost:27017/habit_db
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost